set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

bind -n C-z-k run-shell 'tmux-vim-select-pane -U'
bind -n C-z-j run-shell 'tmux-vim-select-pane -D'
bind -n C-z-h run-shell 'tmux-vim-select-pane -L'
bind -n C-z-l run-shell 'tmux-vim-select-pane -R'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g @dracula-fixed-location "Tirana, Albania"
set -g @dracula-plugins "weather"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session 
set -g status-position top
set -g @dracula-show-fahrenheit false
set -g @dracula-tmux-ram-usage-label "MEM"
set -g @dracula-network-bandwidth eth0
set -g @dracula-network-bandwidth-interval 0
set -g @dracula-network-bandwidth-show-interface true

set -g prefix C-z
unbind-key C-b
bind-key C-z send-prefix

run '~/.tmux/plugins/tpm/tpm' 
